export const ADD_FILE = 'ADD_FILE';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';
export const CANCEL_UPLOADING_FILE = 'CANCEL_UPLOADING_FILE';
export const DELETE_FILE = 'DELETE_FILE';
